spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # 암호화를 하지 않는 다면 jasypt-spring-boot-starter 삭제
    url: ENC(AeEAxdmTq6iYx0G331ReAgPOM2RKij10TBq0y+uUij9EkvY3LkknbMpg3acrSJpg7zIVB2PZ151yLrg7cJUeKSpTurSXF2z1/U1LZdNdY1F1JAP3rn07ng==)
    username: ENC(55grEQB38P24miO+vosUiA==)
    password: ENC(KrW40rwnQ5BSUyyTHlEApK1X2O5joeXa)
    hikari:
      maximum-pool-size: 50
      minimum-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
# 테이블 생성 자동화 및 초기데이터 입력시에만 사용
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/initdata.sql

giljabi:
  eip:
    filePath: x:/git/giljabi/eip/images/
  doc:
    version: 1.0.0

