spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # 암호화를 하지 않는 다면 jasypt-spring-boot-starter 삭제
    url: ENC(6kRPPO7QPsSUOLVEBGtJnLkrd48bhRnNzZpz8KVj4u9OLA0750yoXSxRsrNqOGtXsmZzqds8d3ghdmFyPLTXmLtwwb3DouVX4Rpe4KQx40GoSjKSbi/lCg==)
    username: ENC(wGnxmHJJOZh8UssghkX1E/E03+LTg17G)
    password: ENC(zm4ui4DqkwkkpuZBYOlmvHT+dQqLE+sQ4jN3G9rXveg=)
    hikari:
      maximum-pool-size: 50
      minimum-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
# 테이블 생성 자동화 및 초기데이터 입력시에만 사용
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/initdata.sql

giljabi:
  eip:
    filePath: ~/work/github/eip/images/ #상대경로는 안되고 절대경로로 변경해야 함
  doc:
    version: 1.0.0
