spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/helloworlddb?currentSchema=public&useSSL=false
#    username: hello
#    password: world
    # 암호화를 하지 않는 다면 jasypt-spring-boot-starter 삭제
    url: ENC(fsRjMwqB/bYnoFNTU9exZVjqexLricar65r7QZFjUuJr61sDB1Wk1OYi6TST/LMKzgbC21L9BBz4CmyB6+sVRBlkZkAAdGAroSl/6v228+W6CV9u6tO5hg==)
    username: ENC(Q/GakeXL3tdR3n0gK2wqXg==)
    password: ENC(LuPJiCui2FYMRyFgO8xc/RjQHnJ+lIrv)
    hikari:
      maximum-pool-size: 50
      minimum-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
# 테이블 생성 자동화 및 초기데이터 입력시에만 사용
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/initdata.sql

giljabi:
  eip:
    filePath: ~/work/github/eip/images/
  doc:
    version: 1.0.0
