server:
  port: 8888
  error:
    include-message: always

spring:
  config:
    activate:
      on-profile: localpc, localmac, prod
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  messages:
    basename: messages/messages
    encoding: UTF-8
  session:
    store-type: jdbc
    timeout: 1800
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql

giljabi:
  question:
    max: 5

openai:
  api:
    key: ENC(0Lcv2N9KaHiza/78jYZaL5jK5OaVi31s5OjlYofYBjMEf4+LT3mWW4u/uY9zDZDMU2rIlb8IMs/vvNxOi11ph46w+D76lzXLH6iNy1lgyve03idlK5rebOsQOrLnrAc/WrtT0zKuvaXSGUyTUoYAIRqRqXdzhJ5ESRnZveKsqazLbRn1vsu9SNmDt8xWstT0JcHd6HvpEbTuJUewzHhHqxxEM/u5JbwagCsDWyd3OWc=)
    url: https://api.openai.com/v1/chat/completions
    max: 10000  #일일 사용가능한 토큰수
logging:
  level:
    com.ulisesbocchio.jasyptspringboot.encryptor.DefaultLazyEncryptor: WARN
jwt:
  accessTokenSecret: ENC(EfK1TzoFcfkKSLLRMKzLnnZ14Qps1RKOC/TlVsVwNWOHqms0jVMeaJcnqdyPH0NkGjnf2c8UA5I=)
  accessTokenExpiration: 604800000


