spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # 암호화를 하지 않는 다면 jasypt-spring-boot-starter 삭제
    url: ENC(QJrprnjjNAzDjw4biymOYEGnWboCTqAmd2LvGeU75mY4gyoi7XAflPb3NX57915/r8WKalz5olg+dVoB9E+R0WBlgkBS0nb31dy1GvldBqUzTntM6mI17Q==)
    username:  ENC(w7PQMBnCTR4C+Omakha8Sg==)
    password: ENC(B+xBTMirfoboIVpRtf6lxJ3yCvcqIep/)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # 비활성: 트랜잭션이 종료된 후에도 세션이 열려 있어서, 컨트롤러나 뷰 렌더링 과정에서 지연 로딩(Lazy Loading)된 데이터베이스 조회가 가능합
    open-in-view: false

giljabi:
  eip:
    filePath: /home/ubuntu/apps/eip/build/images/

